@startuml mechanism
skinparam componentStyle rectangle

frame "外部 Angular 应用" {
  [外部 Angular 页面]
  [外部 Angular 扩展组件]
}

frame "Angular Library(React SDK 包裹器）" {
  [Angular 版本的 React Wrapper]
  [React 高阶函数]
}

frame "React SDK"  {
  [React 组件（支持加载扩展 React 组件)]
}

[外部 Angular 页面] *-down-> [Angular 版本的 React Wrapper]
[外部 Angular 扩展组件] -down-> [Angular 版本的 React Wrapper]
[Angular 版本的 React Wrapper] *-down--> [React 组件（支持加载扩展 React 组件)]
[Angular 版本的 React Wrapper] *--> [React 高阶函数]
@enduml
